### ISSUE TITLE
Large model downloading via Audio to text

### ISSUE THREAD

**Issue by Brissinger** [URUWorks/TeroSubtitler#272]
Large v1, 2 or 3 model downloading via Tero Subtitler stucks for me at some point and progress window closes itself before full download. It doesn't go to, like, 0 mb. However if I check model folder there is full file downloaded teoretically so I'm not sure if it is downloaded properly or not.
Latest TeroSubtitler installed, Win11, Ryzen 5 3600, Rtx 3060, 24GB Ram, Lightfiber, Ethernet cable

**Comment by humble-b** [comment]
same here, only when downloading the larger whisper models the download counter showing the bytes to download  shows the amount of bytes downloaded until 1Gb correctly, files larger the counter counts up instead of down and after say 10 mins it goes into failure showing message box it couldn't download. The file downloaded is also showing wrong amount of bytes and is corrupt

version used is ts1015

**Comment by URUWorks** [comment]
please try:
https://github.com/URUWorks/additional-files/raw/main/terosubtitler_testbuild_win64.zip

**Comment by humble-b** [comment]
A bit late but the problem is indeed solved
