### ISSUE TITLE
[multiple] Open video from URL

### ISSUE THREAD

**Issue by chenlung** [URUWorks/TeroSubtitler#35]
There are known issues beyond the control of Tero Subtitler in relation to Open video from URL (i.e. third-party components):
- Extract waveform doesn't work
- Detect doesn't work in Shot Changes
- 'Invalid data found when processing input' (according to debug)
- [This](https://www.youtube.com/watch?v=fMksoZgAoYs) video only plays with sound
- No warning when trying to open a private video (won't play)

**Comment by GitGianluc** [comment]
- Audio to text function causes app to freeze

I would also suggest adding a spinning wheel (or something similar) while the video is being loaded.

**Comment by GitGianluc** [comment]
@URUWorks I believe all of these issues:
> - Extract waveform doesn't work
> - 'Invalid data found when processing input' (according to debug)
> - Audio to text function causes app to freeze

are due to the `Track` field being undefined. Steps to reproduce this bug:

1. Launch Tero Subtitler.
2. Click on `New empty subtitle` on startup.
3. Go to `Video > Open video from URL…` and the dialogue box will open.
4. Paste the URL of the video you wish to be embedded and press _OK_: the video will be loaded shortly (during the process, [should a spinning wheel or something similar be displayed](https://github.com/URUWorks/TeroSubtitler/issues/35#issuecomment-1578458988)?).
5. Go to `Video > Audio to text…` or `Video > Extract waveform…` and the settings' window will open: you will see the `Track` field being empty.
6. Try to press the `Close` button to exit the dialogue box: you will find yourself stuck.

**Comment by GitGianluc** [comment]
> - [This](https://www.youtube.com/watch?v=fMksoZgAoYs) video only plays with sound

Do you mean that you can only hear the sound of the video, but no images?

In my case, the video is visible (excuse the pun):
<img width="1582" alt="Screenshot 2023-06-08 alle 03 28 37" src="https://github.com/URUWorks/TeroSubtitler/assets/16348719/7a0f599b-ee59-4ef9-8baa-cc436d794f0b">

**Comment by chenlung** [comment]
> In my case, the video is visible (excuse the pun):

Thanks for checking. Might be an issue only on Windows (only affected this video for whatever reason), but will try again soon. Would be good to try other OS and hardware.

**Comment by GitGianluc** [comment]
@URUWorks any news on [this topic](https://github.com/URUWorks/TeroSubtitler/issues/35#issuecomment-1581737781)?

**Comment by URUWorks** [comment]
I haven't had time to watch it yet...
